// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjnvrihycsumsayyfwdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqbnZyaWh5Y3N1bXNheXlmd2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzk2NTksImV4cCI6MjA3MjcxNTY1OX0.YM8uPqwSREuVydt-q6WPV8Wqdyiu2KNanPaQNSV6R1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});